### ISSUE TITLE
Typed literals have to be encapsulated into "<...>"

### ISSUE THREAD

**Issue by martinhecher** [DURAARK/pyIfcExtract#1]
The output of the extractor creates lines like the following in using the geo.py utility:

```
duraark:location "http://sws.geonames.org/2867714"^^http://www.w3.org/2003/01/geo/wgs84_pos#SpatialThing ;
```

The line should be like this

```
duraark:location "http://sws.geonames.org/2867714"^^<http://www.w3.org/2003/01/geo/wgs84_pos#SpatialThing> ;
```

where the type is enclosed in "<...>" if it is starting with 'http'.

**Comment by aothms** [comment]
Sorry. That's what you get for not using a proper RDF lib but concatenating string manually.
